apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobile-deploy
  namespace: bookstore-ns
spec:
  selector:
    matchLabels:
      app: mobile-bff
  replicas: 2
  template:
    metadata:
      labels:
        app: mobile-bff
    spec:
      #priorityClassName: high-priority
      containers:
        - name: mobile
          image: charasi/mobile:latest
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /status
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            #timeoutSeconds: 5
            #failureThreshold: 3
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "kubernetes.io/hostname"
                    operator: In
                    values:
                      - worker-0
