---
- name: Install the command line for kubernetes lab on kubernetes controller
  hosts: k8controller
  remote_user: wisccourant
  become: true

  tasks:
    - name: Install CFSSL and kubernetes
      block:
        - name: Install CFSSL needed for PKI infrastructure to generate TLS security
          ansible.builtin.get_url:
            url: "https://github.com/cloudflare/cfssl/releases/download/v1.6.5/cfssl_1.6.5_linux_amd64"
            dest: /home/wisccourant/
            mode: "0600"
          register: cfssl_output

        - name: Print cfssl information from the previous task
          ansible.builtin.debug:
            var: cfssl_output
            verbosity: 0

        - name: Rename to cfssl
          ansible.builtin.command: mv "{{ cfssl_output.dest }}" /home/wisccourant/cfssl
          changed_when: false

        - name: Install CFSSL needed for PKI infrastructure to generate TLS security
          ansible.builtin.get_url:
            url: "https://github.com/cloudflare/cfssl/releases/download/v1.6.5/cfssljson_1.6.5_linux_amd64"
            dest: /home/wisccourant/
            mode: "0600"
          register: cfssljson_output

        - name: Print cfssljson information from the previous task
          ansible.builtin.debug:
            var: cfssljson_output
            verbosity: 0

        - name: Rename to cfssljson
          ansible.builtin.command: mv "{{ cfssljson_output.dest }}" /home/wisccourant/cfssljson
          changed_when: false

        - name: Set cfssl to executable
          ansible.builtin.file:
            path: /home/wisccourant/cfssl
            mode: u+x

        - name: Set cfssljson to executable
          ansible.builtin.file:
            path: /home/wisccourant/cfssljson
            mode: u+x

        - name: Move cfssl to bin directory
          ansible.builtin.command: mv /home/wisccourant/cfssl /usr/local/bin/
          changed_when: false

        - name: Move cfssljson to bin directory
          ansible.builtin.command: mv /home/wisccourant/cfssljson /usr/local/bin/
          changed_when: false

        - name: Download kubectl for lab
          ansible.builtin.command: "curl -LO https://dl.k8s.io/release/v1.32.0/bin/linux/amd64/kubectl"
          changed_when: false
          tags:
            - skip_ansible_lint

        - name: Install Kubectl
          ansible.builtin.command: "install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl"
          changed_when: false
