---
- name: Bootstrapping the Kubernetes Worker Nodes
  hosts: k8workers
  remote_user: wisccourant
  become: true

  tasks:
    - name: Create worker nodes
      block:
        - name: Create directory certificates
          ansible.builtin.file:
            path: /home/wisccourant/certificates/
            state: directory
            mode: "0755"

        - name: Get name of worker -hostname
          ansible.builtin.command:
            cmd: hostname
          register: machine_name
          changed_when: false

        - name: Verify that the machine name was retrieved
          ansible.builtin.assert:
            that:
              - machine_name.stdout | length > 0  # Ensures the content is not empty
            msg: "Could not get machine name"

        - name: Download certificates from gcp
          ansible.builtin.shell: |
            "gsutil cp {{ item.source }} {{ item.dest }}"
          loop:
            - { source: "gs://kthw-misc/{{ machine_name.stdout }}-key.pem", dest: "/home/wisccourant/certificates/" }
            - { source: "gs://kthw-misc/{{ machine_name.stdout }}.pem", dest: "/home/wisccourant/certificates/" }
          changed_when: false
          register: status

        - name: Verify cmd process sucessfully
          ansible.builtin.debug:
            msg: gsutil copied files sucessfully
            var: status
            verbosity: 0
          when: status.rc == 0

        - name: Generate a kubeconfig file for each worker node
          ansible.builtin.shell: |
            set -o pipefail

          args:
            chdir: /home/wisccourant/certificates/
          changed_when: false
