---
- name: Add RBAC for kubelet and kube-proxy
  hosts: k8workers
  remote_user: wisccourant
  become: true

  tasks:
    - name: Retrieve the internal IP address for the current compute instance
      ansible.builtin.command:
        cmd: hostname
      register: host_name
      changed_when: false

    - name: Create custom ClusterRole for worker kubelet
      ansible.builtin.shell: |
        set -o pipefail
        export KUBECONFIG=/var/lib/kubelet/{{ host_name.stdout | trim }}.kubeconfig
        cat <<EOF | kubectl apply -f -
        apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRole
        metadata:
          annotations:
            rbac.authorization.kubernetes.io/autoupdate: "true"
          labels:
            kubernetes.io/bootstrapping: rbac-defaults
          name: {{ host_name.stdout | trim }}-role
        rules:
          - apiGroups:
              - ""
            resources:
              - nodes/proxy
              - nodes/stats
              - nodes/log
              - nodes/spec
              - nodes/metrics
            verbs:
              - "*"
        EOF
      register: rbac_status
      changed_when: false
      args:
        executable: /bin/bash

    - name: Bind custom ClusterRole to worker kubelet
      ansible.builtin.shell: |
        set -o pipefail
        export KUBECONFIG=/var/lib/kubelet/{{ host_name.stdout | trim }}.kubeconfig
        cat <<EOF | kubectl apply -f -
        apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        metadata:
          name: {{ host_name.stdout | trim }}-role-binding
          namespace: ""
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: {{ host_name.stdout | trim }}-role
        subjects:
          - apiGroup: rbac.authorization.k8s.io
            kind: User
            name: {{ host_name.stdout | trim }}
        EOF
      register: rbac_binding_status
      changed_when: false
      args:
        executable: /bin/bash

    - name: Verify ClusterRole and ClusterRoleBinding creation for kubelet
      ansible.builtin.debug:
        var: rbac_status

    - name: Verify ClusterRoleBinding creation for kubelet
      ansible.builtin.debug:
        var: rbac_binding_status

# This part will run only on the kube-proxy node:
- name: Add RBAC for kube-proxy (only on the kube-proxy node)
  hosts: k8worker1  # Define the node where kube-proxy runs in your inventory
  remote_user: wisccourant
  become: true

  tasks:
    - name: Create custom ClusterRole for kube-proxy
      ansible.builtin.shell: |
        set -o pipefail
        export KUBECONFIG=/var/lib/kube-proxy/kube-proxy.kubeconfig
        cat <<EOF | kubectl apply -f -
        apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRole
        metadata:
          annotations:
            rbac.authorization.kubernetes.io/autoupdate: "true"
          labels:
            kubernetes.io/bootstrapping: rbac-defaults
          name: system:kube-proxy
        rules:
          - apiGroups:
              - ""
            resources:
              - nodes/proxy
              - nodes/stats
              - nodes/log
              - nodes/spec
              - nodes/metrics
            verbs:
              - "*"
        EOF
      register: rbac_status
      changed_when: false
      args:
        executable: /bin/bash

    - name: Bind custom ClusterRole to kube-proxy
      ansible.builtin.shell: |
        set -o pipefail
        export KUBECONFIG=/var/lib/kube-proxy/kube-proxy.kubeconfig
        cat <<EOF | kubectl apply -f -
        apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        metadata:
          name: system:kube-proxy
          namespace: ""
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: system:kube-proxy
        subjects:
          - apiGroup: rbac.authorization.k8s.io
            kind: User
            name: kube-proxy
        EOF
      register: rbac_binding_status
      changed_when: false
      args:
        executable: /bin/bash

    - name: Verify ClusterRole and ClusterRoleBinding creation for kube-proxy
      ansible.builtin.debug:
        var: rbac_status

    - name: Verify ClusterRoleBinding creation for kube-proxy
      ansible.builtin.debug:
        var: rbac_binding_status
