---
- name: Add RBAC for scheduler, controller-manager, and reverse
  hosts: k8controller1
  remote_user: wisccourant
  become: true

  tasks:
    - name: Provision the Kubernetes Control Plane
      block:
        - name: Set correct permissions for kubeconfig admin
          ansible.builtin.command:
            cmd: sudo chmod 644 /var/lib/kubernetes/admin.kubeconfig
          register: chmod_status
          changed_when: true

        - name: Create custom ClusterRole for admin
          ansible.builtin.shell: |
            set -o pipefail
            export KUBECONFIG=/var/lib/kubernetes/admin.kubeconfig
            cat <<EOF | kubectl apply -f -
            apiVersion: rbac.authorization.k8s.io/v1
            kind: ClusterRole
            metadata:
              annotations:
                rbac.authorization.kubernetes.io/autoupdate: "true"
              labels:
                kubernetes.io/bootstrapping: rbac-defaults
              name: system:kube-apiserver-to-kubelet
            rules:
              - apiGroups:
                  - ""
                resources:
                  - nodes/proxy
                  - nodes/stats
                  - nodes/log
                  - nodes/spec
                  - nodes/metrics
                verbs:
                  - "*"
            EOF
          register: rbac_status
          changed_when: false
          args:
            executable: /bin/bash

        - name: Bind custom ClusterRole to admin
          ansible.builtin.shell: |
            set -o pipefail
            export KUBECONFIG=/var/lib/kubernetes/admin.kubeconfig
            cat <<EOF | kubectl apply -f -
            apiVersion: rbac.authorization.k8s.io/v1
            kind: ClusterRoleBinding
            metadata:
              name: system:kube-apiserver
            roleRef:
              apiGroup: rbac.authorization.k8s.io
              kind: ClusterRole
              name: system:kube-apiserver-to-kubelet
            subjects:
              - kind: User
                name: kubernetes
                apiGroup: rbac.authorization.k8s.io
            EOF
          register: rbac_binding_status
          changed_when: false
          args:
            executable: /bin/bash

        - name: Create custom ClusterRole for the controller-manager
          ansible.builtin.shell: |
            set -o pipefail
            export KUBECONFIG=/var/lib/kubernetes/admin.kubeconfig
            cat <<EOF | kubectl apply -f -
            apiVersion: rbac.authorization.k8s.io/v1
            kind: ClusterRole
            metadata:
              annotations:
                rbac.authorization.kubernetes.io/autoupdate: "true"
              labels:
                kubernetes.io/bootstrapping: rbac-defaults
              name: controller-manager-role
            rules:
              - apiGroups: [""]
                resources: ["secrets"]
                verbs: ["create", "delete", "get", "update"]

              - apiGroups: [""]
                resources: ["serviceaccounts"]
                verbs: ["create", "get", "update"]

              - apiGroups: [""]
                resources: ["events"]
                verbs: ["create", "patch", "update"]

              - apiGroups: ["events.k8s.io"]
                resources: ["events"]
                verbs: ["create", "patch", "update"]

              - apiGroups: [""]
                resources: ["serviceaccounts/token"]
                verbs: ["create"]

              - apiGroups: ["authentication.k8s.io"]
                resources: ["tokenreviews"]
                verbs: ["create"]

              - apiGroups: ["authorization.k8s.io"]
                resources: ["subjectaccessreviews"]
                verbs: ["create"]

              - apiGroups: ["coordination.k8s.io"]
                resources: ["leases"]
                verbs: ["create"]

              - apiGroups: ["coordination.k8s.io"]
                resources: ["leases"]
                resourceNames: ["kube-controller-manager"]
                verbs: ["get", "update"]

              - apiGroups: [""]
                resources: ["configmaps"]
                verbs: ["get"]

              - apiGroups: [""]
                resources: ["namespaces"]
                verbs: ["get"]

              - apiGroups: ["*"]
                resources: ["*"]
                verbs: ["list", "watch"]
            EOF
          register: rbac_status
          changed_when: false
          args:
            executable: /bin/bash

        - name: Bind custom ClusterRole to controller
          ansible.builtin.shell: |
            set -o pipefail
            export KUBECONFIG=/var/lib/kubernetes/admin.kubeconfig
            cat <<EOF | kubectl apply -f -
            apiVersion: rbac.authorization.k8s.io/v1
            kind: ClusterRoleBinding
            metadata:
              name: system:controller-manager-binding
            roleRef:
              apiGroup: rbac.authorization.k8s.io
              kind: ClusterRole
              name: controller-manager-role
            subjects:
              - kind: User
                name: system:controller-manager
                apiGroup: rbac.authorization.k8s.io
            EOF
          register: rbac_binding_status
          changed_when: false
          args:
            executable: /bin/bash

