apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deploy
  namespace: bookstore-ns
spec:
  selector:
    matchLabels:
      app: kafka
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
    spec:
      #priorityClassName: high-priority
      containers:
        - name: kafka
          image: charasi/kafka:latest
          ports:
            - containerPort: 8080
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - kafka
